name = "observatorio-2030-push"
main = "src/index.js"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "observatorio-2030-push"
database_id = "771674ef-7448-40bc-8726-750902d3d468"

[vars]
ALLOWED_ORIGIN = "https://jjdsnt.github.io"
